# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1M3Hi0H14zYdtFgLjRZrmkTXWF28srFxs
"""

# app.py
import streamlit as st
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

# Set Streamlit page configuration
st.set_page_config(page_title="University Dashboard", layout="wide")

# Load dataset
df = pd.read_csv("university_student_data.csv")

# Page title
st.title("University Student Data Dashboard")

# Show dataset preview
with st.expander("View dataset"):
    st.dataframe(df.head())

# User can filter by year and term
year = st.selectbox("Select Year", sorted(df["Year"].unique()))
term = st.selectbox("Select Term", sorted(df["Term"].unique()))

# Apply filters
filtered = df[(df["Year"] == year) & (df["Term"] == term)]

st.subheader("Key Indicators")

col1, col2, col3 = st.columns(3)
col1.metric("Applications", int(filtered["Applications"].sum()))
col2.metric("Admitted", int(filtered["Admitted"].sum()))
col3.metric("Enrolled", int(filtered["Enrolled"].sum()))

# Visualization 1: Retention Rate Over Time
st.subheader("Retention Rate Over Time")
fig1, ax1 = plt.subplots()
sns.lineplot(data=df, x="Year", y="Retention Rate (%)", marker="o", ax=ax1)
ax1.set_ylabel("Retention Rate (%)")
ax1.set_title("Retention Rate by Year")
st.pyplot(fig1)

# Visualization 2: Student Satisfaction Over Time
st.subheader("Average Student Satisfaction by Year")
avg_satisfaction = df.groupby("Year")["Student Satisfaction (%)"].mean().reset_index()
fig2, ax2 = plt.subplots()
sns.barplot(data=avg_satisfaction, x="Year", y="Student Satisfaction (%)", ax=ax2)
ax2.set_ylabel("Satisfaction (%)")
ax2.set_title("Average Student Satisfaction by Year")
st.pyplot(fig2)

# Visualization 3: Enrollment Distribution by Department
st.subheader("Enrollment Distribution by Department")

# Sum all department columns for selected filters
dept_data = {
    "Engineering": filtered["Engineering Enrolled"].sum(),
    "Business": filtered["Business Enrolled"].sum(),
    "Arts": filtered["Arts Enrolled"].sum(),
    "Science": filtered["Science Enrolled"].sum(),
}

fig3, ax3 = plt.subplots()
ax3.pie(dept_data.values(), labels=dept_data.keys(), autopct="%1.1f%%", startangle=90)
ax3.set_title(f"Enrollment by Department ({term} {year})")
st.pyplot(fig3)

# Footer
st.markdown("---")
st.caption("Developed for Data Visualization & Dashboard Deployment - Universidad de la Costa")